name: conchayoro-pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Contents
        run: cat index.html

      - name: Deploy to S3
        run: |
          aws s3 cp ./index.html s3://$BUCKET_S3 --acl public-read
          echo "AWS CLI Version:"
          aws --version
          echo "List S3 Contents:"
          aws s3 ls s3://$BUCKET_S3/
