name: conchayoro-pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files in Directory
        run: ls -R

      - name: Setup Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install 16
          node --version

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: .  # Upload all files in the current directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node.js
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
          nvm install 16
          node --version

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy
          path: .  # Download all files in the artifact to the current directory

      - name: Upload to S3
        run: aws s3 cp ./index.html s3://$BUCKET_S3 --recursive --acl public-read
