name: conchayoro-pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Files in Directory
        run: ls -R

      - name: Upload Artifact
        if: success()  # Upload artifact only if previous steps were successful
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: .  # Upload all files in the current directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy
          path: .  # Download all files in the artifact to the current directory

      - name: Check if index.html exists
        run: test -e index.html

      - name: Upload to S3
        if: success()  # Upload to S3 only if the previous step was successful
        run: aws s3 cp ./index.html s3://$BUCKET_S3 --recursive --acl public-read
