name: conchayoro-pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List Files in Directory
        run: ls -R

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy
          path: .  # Upload all files in the current directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy
          path: .  # Download all files in the artifact to the current directory

      - name: Upload to S3
        run: aws s3 cp ./index.html s3://$BUCKET_S3 --recursive --acl public-read
