name: conchayoro-pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      BUCKET_S3: ${{ secrets.BUCKET_S3 }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Contents
        run: ls -R

      - name: Check if index.html exists
        run: test -e index.html || echo "File not found"

      - name: Deploy to S3
        run: |
          if [ -e "index.html" ]; then
            aws s3 cp ./index.html s3://$BUCKET_S3 --acl public-read
          else
            echo "File not found. Deployment skipped."
          fi
